# Generated by Django 2.2.5 on 2021-04-28 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20210425_2313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='Check_out',
            new_name='check_out',
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='rooms.RoomType'),
        ),
    ]
