# Generated by Django 2.2.5 on 2021-08-06 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_auto_20210502_1918'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomtype',
            options={'verbose_name': 'Room Types'},
        ),
    ]
